services:
  transmission:
    image: linuxserver/transmission:4.1.0
    container_name: transmission
    devices:
      - /dev/net/tun
    volumes:
      - ${BASE_PATH}/config/transmission-home:/config
      - /data:/transcend # All the media containers use transcend internally because that's what i set originally. It's too much work to change it now.
    depends_on:
      - wireguard
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
      PEERPORT: 54914
    restart: unless-stopped
    network_mode: "service:wireguard"
    labels:
      autoheal: true

